2021-01-08 18:44:46,768:utils.oauth:ERROR:HTTPSConnectionPool(host='pocketfactory-hbc.ssidecisions.com', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8431605C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2021-01-08 18:45:18,193:utils.oauth:ERROR:HTTPSConnectionPool(host='pocketfactory-hbc.ssidecisions.com', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C245B2D3C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2021-01-08 18:46:31,740:utils.oauth:ERROR:HTTPSConnectionPool(host='pocketfactory-hbc.ssidecisions.com', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000243E6518348>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
