2020-08-28 15:50:13,713:utils.oauth:ERROR:HTTPSConnectionPool(host='pocketfactory-hbc.ssidecisions.com', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021557B77B08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-08-28 15:51:10,183:utils.oauth:ERROR:HTTPSConnectionPool(host='pocketfactory-hbc.ssidecisions.com', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028CEBCD64C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
